CREATE TYPE "WeeklyPlanStatus" AS ENUM ('DRAFT', 'CONFIRMED', 'CLOSED');
CREATE TYPE "RoutineBlockType" AS ENUM ('RANKED', 'AIM_TRAINING', 'VOD_REVIEW', 'COACHING', 'COMPETITIVE', 'THEORY', 'FREE', 'COMMITMENT', 'OTHER');
CREATE TYPE "RoutineBlockStatus" AS ENUM ('DRAFT', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED');
CREATE TYPE "TrainingSessionStatus" AS ENUM ('IN_PROGRESS', 'PAUSED', 'COMPLETED', 'CANCELLED');
CREATE TABLE "WeeklyPlan" ("id" UUID NOT NULL, "userId" UUID NOT NULL, "weekStart" DATE NOT NULL, "weekEnd" DATE NOT NULL, "status" "WeeklyPlanStatus" NOT NULL DEFAULT 'DRAFT', "rankedTargetMin" INTEGER NOT NULL, "rankedTargetMax" INTEGER NOT NULL, "weeklyIntent" TEXT NOT NULL, "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(3) NOT NULL, CONSTRAINT "WeeklyPlan_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RoutineBlock" ("id" UUID NOT NULL, "weeklyPlanId" UUID NOT NULL, "userId" UUID NOT NULL, "focusAreaId" UUID, "type" "RoutineBlockType" NOT NULL, "status" "RoutineBlockStatus" NOT NULL DEFAULT 'DRAFT', "title" VARCHAR(160) NOT NULL, "plannedStart" TIMESTAMPTZ(3) NOT NULL, "plannedEnd" TIMESTAMPTZ(3) NOT NULL, "notes" TEXT, "cancellationReason" TEXT, "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(3) NOT NULL, CONSTRAINT "RoutineBlock_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TrainingSession" ("id" UUID NOT NULL, "userId" UUID NOT NULL, "plannedBlockId" UUID, "focusAreaId" UUID, "type" "RoutineBlockType" NOT NULL, "startedAt" TIMESTAMPTZ(3) NOT NULL, "endedAt" TIMESTAMPTZ(3), "status" "TrainingSessionStatus" NOT NULL DEFAULT 'IN_PROGRESS', "pausedAt" TIMESTAMPTZ(3), "totalPausedSeconds" INTEGER NOT NULL DEFAULT 0, "preEnergy" INTEGER, "preFocus" INTEGER, "overallConcentration" INTEGER, "focusAdherence" INTEGER, "mainLearning" TEXT, "nextAdjustment" TEXT, "mentalState" TEXT, "cancellationReason" TEXT, "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(3) NOT NULL, CONSTRAINT "TrainingSession_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "WeeklyPlan_userId_weekStart_key" ON "WeeklyPlan"("userId", "weekStart");
CREATE INDEX "WeeklyPlan_userId_status_idx" ON "WeeklyPlan"("userId", "status");
CREATE INDEX "RoutineBlock_weeklyPlanId_plannedStart_idx" ON "RoutineBlock"("weeklyPlanId", "plannedStart");
CREATE INDEX "RoutineBlock_userId_status_idx" ON "RoutineBlock"("userId", "status");
CREATE UNIQUE INDEX "TrainingSession_plannedBlockId_key" ON "TrainingSession"("plannedBlockId");
CREATE INDEX "TrainingSession_userId_status_idx" ON "TrainingSession"("userId", "status");
CREATE INDEX "TrainingSession_userId_startedAt_idx" ON "TrainingSession"("userId", "startedAt");
CREATE UNIQUE INDEX "TrainingSession_single_active_user_idx" ON "TrainingSession"("userId") WHERE "status" IN ('IN_PROGRESS', 'PAUSED');
ALTER TABLE "WeeklyPlan" ADD CONSTRAINT "WeeklyPlan_ranked_targets_check" CHECK ("rankedTargetMin" >= 0 AND "rankedTargetMax" >= "rankedTargetMin");
ALTER TABLE "RoutineBlock" ADD CONSTRAINT "RoutineBlock_interval_check" CHECK ("plannedEnd" > "plannedStart");
ALTER TABLE "WeeklyPlan" ADD CONSTRAINT "WeeklyPlan_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RoutineBlock" ADD CONSTRAINT "RoutineBlock_weeklyPlanId_fkey" FOREIGN KEY ("weeklyPlanId") REFERENCES "WeeklyPlan"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RoutineBlock" ADD CONSTRAINT "RoutineBlock_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RoutineBlock" ADD CONSTRAINT "RoutineBlock_focusAreaId_fkey" FOREIGN KEY ("focusAreaId") REFERENCES "FocusArea"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TrainingSession" ADD CONSTRAINT "TrainingSession_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TrainingSession" ADD CONSTRAINT "TrainingSession_plannedBlockId_fkey" FOREIGN KEY ("plannedBlockId") REFERENCES "RoutineBlock"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TrainingSession" ADD CONSTRAINT "TrainingSession_focusAreaId_fkey" FOREIGN KEY ("focusAreaId") REFERENCES "FocusArea"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
